version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .datagov/Dockerfile
    volumes:
      - virtualenvs:/home/pycsw/.virtualenvs
      - .:/home/pycsw/pycsw

volumes:
  virtualenvs:
