version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - setup_remote_docker
      - run: docker-compose -f docker-compose.yml -f docker-compose.test.yml build
      - run: docker-compose -f docker-compose.yml -f docker-compose.test.yml run --rm app pipenv run pycsw-ckan.py -c setup_db -f /etc/pycsw/pycsw.cfg
      - run: docker-compose -f docker-compose.yml -f docker-compose.test.yml up --abort-on-container-exit test


workflows:
  version: 2
  commit:
    jobs:
      - build
